

--Implement AFTER Triggers for Automatic Execution After Data Operations
--EMPLOYEE_LOG (LOGID, EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
--From the table EMPLOYEE perform the following queries:


--Part – A:

--1. AFTER INSERT TRIGGER TO PRINT MESSAGE
CREATE TRIGGER TRG_EMP_INSERT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    PRINT 'EMPLOYEE RECORD INSERTED SUCCESSFULLY';
END;

--2. AFTER UPDATE TRIGGER TO PRINT MESSAGE
CREATE TRIGGER TRG_EMP_UPDATE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    PRINT 'EMPLOYEE RECORD UPDATED SUCCESSFULLY';
END;

--3. AFTER DELETE TRIGGER TO PRINT MESSAGE
CREATE TRIGGER TRG_EMP_DELETE
ON EMPLOYEE
AFTER DELETE
AS
BEGIN
    PRINT 'EMPLOYEE RECORD DELETED SUCCESSFULLY';
END;

--4. AFTER UPDATE TRIGGER FOR SALARY INCREMENT
CREATE TRIGGER TRG_EMP_SALARY_INCREMENT
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    IF UPDATE(SALARY)
        PRINT 'EMPLOYEE SALARY INCREMENTED SUCCESSFULLY';
END;

--5. AFTER INSERT TRIGGER TO CONVERT CITY INTO UPPERCASE
CREATE TRIGGER TRG_EMP_CITY_UPPERCASE
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE EMPLOYEE
    SET CITY = UPPER(CITY)
    WHERE EID IN (SELECT EID FROM INSERTED);
END;


--Part – B:

--6. Create trigger for updating employee city and printing old city and new city name.
CREATE TRIGGER TRG_EMP_CITY_UPDATE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    IF UPDATE(CITY)
    BEGIN
        SELECT DELETED.CITY AS OLD_CITY, INSERTED.CITY AS NEW_CITY
        FROM DELETED INNER JOIN INSERTED ON DELETED.EID = INSERTED.EID;
        PRINT 'EMPLOYEE CITY UPDATED SUCCESSFULLY';
    END
END;


--7. Create trigger for automatically setting CITY as 'RAJKOT' if no city value is entered during employee insertion.
CREATE TRIGGER TRG_EMP_CITY_DEFAULT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE EMPLOYEE
    SET CITY = 'RAJKOT'
    WHERE EID IN (SELECT EID FROM INSERTED) AND CITY IS NULL;
END;

--8. Create trigger for automatically adding current year in JOININGYEAR if no value is entered.
CREATE TRIGGER TRG_EMP_JOININGYEAR_DEFAULT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE EMPLOYEE
    SET JOININGYEAR = YEAR(GETDATE())
    WHERE EID IN (SELECT EID FROM INSERTED) AND JOININGYEAR IS NULL;
END;

--9. Create trigger for printing employee full name after new employee insertion.
CREATE TRIGGER TRG_EMP_FULLNAME_PRINT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    DECLARE @FULLNAME VARCHAR(100);
    SELECT @FULLNAME = FIRSTNAME + ' ' + LASTNAME FROM INSERTED;
    PRINT 'NEW EMPLOYEE INSERTED: ' + @FULLNAME;
END;

--10. Create trigger for automatically assigning department as ‘GENERAL’ if DEPARTMENT value is NULL.
CREATE TRIGGER TRG_EMP_DEPT_DEFAULT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    UPDATE EMPLOYEE
    SET DEPARTMENT = 'GENERAL'
    WHERE EID IN (SELECT EID FROM INSERTED) AND DEPARTMENT IS NULL;
END;

--Part – C:

CREATE TABLE EMPLOYEE_LOG (
    LOGID INT IDENTITY(1,1) PRIMARY KEY,
    EID INT,
    OLDVALUE VARCHAR(100),
    NEWVALUE VARCHAR(100),
    FIELDNAME VARCHAR(50),
    OPERATIONTYPE VARCHAR(50),
    LOGDATE DATETIME
);

CREATE TABLE EMPLOYEE_UPDATE_LOG (
    EID INT,
    OLDSALARY DECIMAL(18,2),
    NEWSALARY DECIMAL(18,2),
    OLDDEPARTMENT VARCHAR(50),
    NEWDEPARTMENT VARCHAR(50),
    UPDATEDATE DATETIME
);

CREATE TABLE EMPLOYEE_UPDATE_LOG2 (
    ID INT,
    OLDSALARY DECIMAL(18,2),
    NEWSALARY DECIMAL(18,2),
    OLDDEPARTMENT VARCHAR(50),
    NEWDEPARTMENT VARCHAR(50),
    UPDATEDATE DATETIME
);



CREATE TABLE EMPLOYEE_INSERT_LOG (
    EID INT,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(8,2),
    CITY VARCHAR(50),
    GENDER VARCHAR(10),
    JOININGYEAR INT,
    INSERTDATE DATETIME
);

CREATE TABLE NAME_CHANGE_LOG (
    EID INT,
    OLDFIRSTNAME VARCHAR(50),
    NEWFIRSTNAME VARCHAR(50),
    UPDATEDATE DATETIME
);

CREATE TABLE CITY_UPDATE_LOG (
    EID INT,
    OLDCITY VARCHAR(50),
    NEWCITY VARCHAR(50),
    UPDATEDATE DATETIME
);

--11. Create trigger for storing updated employee details such as EID, old salary, new salary, old department, new department, and update date into EMPLOYEE_UPDATE_LOG table.
CREATE OR ALTER TRIGGER TRG_SHOW_DETAILS
ON EMPLOYEE
AFTER UPDATE 
AS 
BEGIN
    IF UPDATE(SALARY)
    BEGIN
        INSERT INTO EMPLOYEE_UPDATE_LOG2
        (ID, OLDSALARY, NEWSALARY, OLDDEPARTMENT, NEWDEPARTMENT,  UPDATEDATE)

        SELECT I.EID , D.SALARY,I.SALARY,D.DEPARTMENT,I.DEPARTMENT,GETDATE()
        FROM INSERTED I
        INNER JOIN DELETED D 
        ON I.EID = D.EID
    END
END

SELECT * FROM EMPLOYEE_UPDATE_LOG2

--12. AFTER INSERT TRIGGER TO STORE NEW EMPLOYEE DETAILS IN EMPLOYEE_INSERT_LOG
CREATE TRIGGER TRG_EMP_INSERT_LOG
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_INSERT_LOG(EID, FIRSTNAME, LASTNAME, DEPARTMENT, CITY, SALARY, INSERT_DATE)
    SELECT EID, FIRSTNAME, LASTNAME, DEPARTMENT, CITY, SALARY, GETDATE()
    FROM INSERTED;
END;

--13. AFTER UPDATE TRIGGER TO STORE OLD AND NEW FIRSTNAME IN NAME_CHANGE_LOG
CREATE TRIGGER TRG_EMP_NAME_CHANGE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    IF UPDATE(FIRSTNAME)
    BEGIN
        INSERT INTO NAME_CHANGE_LOG(EID, OLD_FIRSTNAME, NEW_FIRSTNAME, CHANGE_DATE)
        SELECT D.EID, D.FIRSTNAME, I.FIRSTNAME, GETDATE()
        FROM DELETED D INNER JOIN INSERTED I ON D.EID = I.EID;
    END
END;

--14. AFTER UPDATE TRIGGER TO STORE OLD AND NEW CITY IN CITY_UPDATE_LOG
CREATE TRIGGER TRG_EMP_CITY_CHANGE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    IF UPDATE(CITY)
    BEGIN
        INSERT INTO CITY_UPDATE_LOG(EID, OLD_CITY, NEW_CITY, CHANGE_DATE)
        SELECT D.EID, D.CITY, I.CITY, GETDATE()
        FROM DELETED D INNER JOIN INSERTED I ON D.EID = I.EID;
    END
END;

--15. INSTEAD OF INSERT TRIGGER TO REMOVE EXTRA SPACES FROM FIRSTNAME AND LASTNAME
CREATE TRIGGER TRG_EMP_REMOVE_SPACES
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE(EID, FIRSTNAME, LASTNAME, DEPARTMENT, CITY, SALARY, JOININGYEAR)
    SELECT EID, LTRIM(RTRIM(FIRSTNAME)), LTRIM(RTRIM(LASTNAME)), DEPARTMENT, CITY, SALARY, JOININGYEAR
    FROM INSERTED;
END;


















































