-- PART A : BASIC RETRIEVAL FUNCTIONS

-- Q1. DISPLAY ALL STUDENT RECORDS
CREATE FUNCTION FN_ALLSTUDENTS()
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT
);

-- Q2. STUDENTS BY CITY
CREATE FUNCTION FN_STUDENTSBYCITY(@CITY VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE CITY = @CITY
);

-- Q3. STUDENTS BY BRANCH
CREATE FUNCTION FN_STUDENTSBYBRANCH(@BRANCH VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE BRANCH = @BRANCH
);

-- Q4. STUDENTS WITH SPI > GIVEN VALUE
CREATE FUNCTION FN_STUDENTSBYSPI(@SPI DECIMAL(4,2))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE SPI > @SPI
);

-- Q5. STUDENTS WITH SPI IN RANGE
CREATE FUNCTION FN_STUDENTSBYSPIRANGE(@MIN_SPI DECIMAL(4,2), @MAX_SPI DECIMAL(4,2))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE SPI BETWEEN @MIN_SPI AND @MAX_SPI
);

-- PART B : CONDITIONAL FUNCTIONS

-- Q6. STUDENT DETAILS BY STDID
CREATE FUNCTION FN_STUDENTBYID(@STDID INT)
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE STDID = @STDID
);

-- Q7. STUDENTS FROM CITY WITH SPI > 7
CREATE FUNCTION FN_CITYSPI(@CITY VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE CITY = @CITY AND SPI > 7
);

-- Q8. STUDENTS FROM BRANCH WITH SPI < 8
CREATE FUNCTION FN_BRANCHSPI(@BRANCH VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE BRANCH = @BRANCH AND SPI < 8
);

-- Q9. TOP N STUDENTS BY SPI
CREATE FUNCTION FN_TOPNSTUDENTS(@TOPN INT)
RETURNS TABLE
AS
RETURN (
    SELECT TOP(@TOPN) * FROM STUDENT ORDER BY SPI DESC
);

-- Q10. HIGHEST SPI STUDENT FROM BRANCH
CREATE FUNCTION FN_HIGHESTSPIBYBRANCH(@BRANCH VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT TOP 1 * FROM STUDENT WHERE BRANCH = @BRANCH ORDER BY SPI DESC
);


-- PART C : AGGREGATES & RANKING

-- Q11. TOTAL STUDENTS FROM CITY
CREATE FUNCTION FN_TOTALSTUDENTSBYCITY(@CITY VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT CITY, COUNT(*) AS TOTALSTUDENTS
    FROM STUDENT
    WHERE CITY = @CITY
    GROUP BY CITY
);

-- Q12. STUDENTS FROM BRANCH ORDERED BY SPI
CREATE FUNCTION FN_BRANCHORDER(@BRANCH VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT WHERE BRANCH = @BRANCH ORDER BY SPI DESC
);

-- Q13. TOP 3 STUDENTS FROM CITY BY SPI
CREATE FUNCTION FN_TOP3CITY(@CITY VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT TOP 3 * FROM STUDENT WHERE CITY = @CITY ORDER BY SPI DESC
);

-- Q14. STUDENT RANK BY SPI
CREATE FUNCTION FN_STUDENTRANK(@STDID INT)
RETURNS TABLE
AS
RETURN (
    SELECT STDID, SNAME, SPI,
           RANK() OVER (ORDER BY SPI DESC) AS RANKNO
    FROM STUDENT
    WHERE STDID = @STDID
);

-- Q15. SECOND HIGHEST SPI STUDENT FROM BRANCH
CREATE FUNCTION FN_SECONDHIGHESTSPIBYBRANCH(@BRANCH VARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM STUDENT
    WHERE BRANCH = @BRANCH
      AND SPI = (
          SELECT MAX(SPI) 
          FROM STUDENT 
          WHERE BRANCH = @BRANCH
            AND SPI < (SELECT MAX(SPI) FROM STUDENT WHERE BRANCH = @BRANCH)
      )
);