
--lab22
--Implement Advance Common Table Expressions (CTE) for Query Simplification

--------------------CUSTOMER_ALL-----------------

CREATE TABLE CUSTOMER_ALL
(
    ORDERID INT PRIMARY KEY,
    CNAME VARCHAR(30),
    PRODUCT VARCHAR(30),
    CATEGORY VARCHAR(30),
    AMOUNT DECIMAL(10,2),
    ORDERYEAR INT,
    CITY VARCHAR(30)
);

INSERT INTO CUSTOMER_ALL VALUES
(101,'RAHUL','LAPTOP','ELECTRONICS',65000,2024,'RAJKOT'),
(102,'PRIYA','MOBILE','ELECTRONICS',25000,2023,'SURAT'),
(103,'AMIT','TABLE','FURNITURE',12000,2022,'AHMEDABAD'),
(104,'NEHA','CHAIR','FURNITURE',8000,2024,'BARODA'),
(105,'VISHAL','TV','ELECTRONICS',45000,2025,'MORBI'),
(106,'RIYA','SOFA','FURNITURE',30000,2023,'SURAT'),
(107,'MEHUL','AC','ELECTRONICS',40000,2022,'RAJKOT'),
(108,'KRUNAL','BED','FURNITURE',40000,2025,'JAMNAGAR');

SELECT * FROM CUSTOMER_ALL

--Part – A:
--1. Display top 3 highest amount orders.
WITH CTE AS (
    SELECT ORDERID, CNAME, AMOUNT,
           RANK() OVER (ORDER BY AMOUNT DESC) AS raank
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE WHERE raank <= 3;

--2. Display second highest order amount.
WITH CTE AS (
    SELECT ORDERID, CNAME, AMOUNT,
           RANK() OVER (ORDER BY AMOUNT DESC) AS second_raank
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE WHERE second_raank = 2;

--3. Display customers whose order amount is greater than category average amount.
WITH CTE AS (
    SELECT *,AVG(AMOUNT) OVER(PARTITION BY CATEGORY) AS AVG_AMOUNT
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE 

WHERE AMOUNT > AVG_AMOUNT

--4. Display categories having average amount greater than 30000.
WITH CTE AS (
    SELECT AVG(AMOUNT) AS A
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT *
FROM CTE 
WHERE  A > 30000

-- 5. Highest amount order from each category
WITH CTE AS (
    SELECT *, RANK() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT DESC)   AS MAX_AMOUNT
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE
WHERE MAX_AMOUNT = 1;

-- 6. LOWEST AMOUNT ORDER FROM EACH CATEGORY
WITH CTE AS (
    SELECT *, RANK() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT ASC)   AS MIN_AMOUNT
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE
WHERE MIN_AMOUNT = 1;

-- 7. CATEGORIES HAVING MORE THAN 3 ORDERS
WITH CTE AS (
    SELECT CATEGORY, COUNT(*) AS ORDERCOUNT
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT * FROM CTE 
WHERE ORDERCOUNT > 3

--8. Display city-wise total order amount.
WITH CITYTOTAL AS (
    SELECT CITY, SUM(AMOUNT) AS TOTALAMT
    FROM CUSTOMER_ALL
    GROUP BY CITY
)
SELECT * FROM CITYTOTAL;

--9. Display category having highest average order amount.
WITH CTE AS (
    SELECT CATEGORY, AVG(AMOUNT) AS AVGG,
    RANK() OVER(ORDER BY AVG(AMOUNT) DESC) AS RNK
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT * FROM CTE
WHERE RNK = 1;

--10. Display cumulative order amount in ascending order of amount.
WITH CTE AS
(
SELECT *,SUM(AMOUNT) OVER
(
ORDER BY AMOUNT
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)AS RNK
FROM CUSTOMER_ALL
)
SELECT * FROM CTE 
ORDER BY AMOUNT

--Part – B:
-- 11. CATEGORY-WISE TOP 2 HIGHEST AMOUNT ORDERS
WITH CTE AS (
    SELECT CATEGORY, ORDERID, CNAME, AMOUNT,
           RANK() OVER (PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS RNK
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE WHERE RNK <= 2;

-- 12. CUSTOMERS CLOSEST TO CATEGORY AVERAGE
WITH CTE AS (

)
-- 13. PREVIOUS, CURRENT, NEXT ORDER AMOUNT
WITH CTE AS (
    SELECT ORDERID, CNAME, AMOUNT,
           LAG(AMOUNT) OVER (ORDER BY ORDERID) AS PREVAMT,
           LEAD(AMOUNT) OVER (ORDER BY ORDERID) AS NEXTAMT
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE;

-- 14. CUSTOMERS WHOSE AMOUNT > PREVIOUS CUSTOMER
WITH CTE AS (
    SELECT CNAME, AMOUNT,
           LAG(AMOUNT) OVER (ORDER BY ORDERID) AS PREVAMT
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE WHERE AMOUNT > PREVAMT;

-- 15. CUSTOMERS WHERE RANK <> DENSE RANK
WITH CTE AS (
    SELECT CNAME, AMOUNT,
           RANK() OVER (ORDER BY AMOUNT DESC) AS RNK,
           DENSE_RANK() OVER (ORDER BY AMOUNT DESC) AS DRNK
    FROM CUSTOMER_ALL
)
SELECT * FROM CTE WHERE RNK <> DRNK;

--Part – C:
--16. Display orders whose amount is neither highest nor lowest in their category. 
	WITH AMOUNT AS (
					SELECT *,
					RANK() OVER( PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS MAX,						
					RANK() OVER( PARTITION BY CATEGORY ORDER BY AMOUNT) AS MIN						
					FROM CUSTOMER_ALL
				)

	SELECT * 
	FROM  AMOUNT 
	WHERE MAX<>1 AND MIN<>1; 

--17. Display category-wise difference between highest and lowest amount.
	WITH AMOUNT_DIFF AS (
						SELECT CATEGORY,
						( MAX(AMOUNT) - MIN(AMOUNT) ) AS DIFF
						FROM CUSTOMER_ALL
						GROUP BY CATEGORY )

	SELECT * FROM AMOUNT_DIFF; 
	
--18. Display customers whose amount is greater than all FURNITURE category orders.
	WITH HIGH_AMOUNT AS (
						SELECT MAX(AMOUNT) AS MAX						
						FROM CUSTOMER_ALL
						WHERE CATEGORY = 'FURNITURE' )

	SELECT C.* 
	FROM CUSTOMER_ALL C
	CROSS JOIN HIGH_AMOUNT H
	WHERE C.AMOUNT > H.MAX; 

--19. Display categories where all orders are above 10000.
	WITH AMOUNT AS (
						SELECT CATEGORY, MIN(AMOUNT) AS MIN						
						FROM CUSTOMER_ALL
						GROUP BY  CATEGORY )

	SELECT CATEGORY FROM AMOUNT 
	WHERE MIN > 10000;
	
--20. Display customers whose amount difference from category topper is minimum.
	WITH CLOSET_AMOUNT AS (
							SELECT *,
							ABS(AMOUNT-MAX(AMOUNT) OVER (PARTITION BY CATEGORY) )AS DIFF FROM CUSTOMER_ALL )

	SELECT *
	FROM CLOSET_AMOUNT 
	WHERE DIFF IN (
					SELECT MIN(DIFF)
					FROM CLOSET_AMOUNT
					GROUP BY CATEGORY )  
	